[package]
name = "method_tryout"
version = "0.1.0"
authors = ["Warut Surapat <s.warut@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
